CREATE TABLE membership (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  homepage TEXT NOT NULL,
  domain TEXT NOT NULL,
  contact TEXT NOT NULL,
  total_referrer UNSIGNED BIGINT DEFAULT 0 NOT NULL,
  description TEXT NOT NULL
);
CREATE UNIQUE INDEX idx_membership_domain ON membership (domain);
