CREATE TABLE membership (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  homepage TEXT NOT NULL,
  domain TEXT NOT NULL,
  contact TEXT NOT NULL,
  total_referrer INTEGER  DEFAULT 0 NOT NULL,
  description TEXT NOT NULL
);