CREATE TABLE trending (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  membership_id INTEGER DEFAULT 0 NOT NULL,
  page_view INTEGER DEFAULT 0 NOT NULL,
  referrer INTEGER DEFAULT 0 NOT NULL
);
CREATE INDEX idx_trending_membership_id ON trending (membership_id);
