CREATE TABLE trending (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  membership_id UNSIGNED BIGINT DEFAULT 0 NOT NULL,
  page_view UNSIGNED BIGINT DEFAULT 0 NOT NULL,
  referrer UNSIGNED BIGINT DEFAULT 0 NOT NULL
);
CREATE INDEX idx_trending_membership_id ON trending (membership_id);
